AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - script/**
  TargetRubyVersion: 3.0.2
  NewCops: enable

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 100
